### ISSUE TITLE
能认识一下吗

### ISSUE THREAD

**Issue by huangsuhao** [liuchuo/Book-sales-management-system#1]
我是一个写iOS的弱鸡 刚好最近也在刷pat和蓝桥
能认识一下吗 互相交流
weibo@喵哩嗷 （只有微博不是隐私的 如果可以的话想认识一下>  。<）

**Comment by liuchuo** [comment]
不用微博怎么破……

**Comment by huangsuhao** [comment]
摊手 QQ微信都好呀 你用哪个


发自网易邮箱大师
在2017年04月05日 10:28，柳婼<mailto:notifications@github.com> 写道：

不用微博怎么破……

**Comment by liuchuo** [comment]
都不太常用……微信号：wojiaobendandan
